### PR TITLE
Ensure tables exists in internal db

### PR DESCRIPTION
**Pull request by eneemann**
I added some checks to workspace_info.py to remove tables from the fc_list that don't exist in the internal sgid.  This PR addresses issue #90.

### CODE REVIEW

**Review by steveoh — CHANGES_REQUESTED** [review]
I would prefer if you didn't use `os.path` for any new code written.

**Comment by eneemann** [comment]
> I would prefer if you didn't use `os.path` for any new code written.

I thought you said Path didn't play nice with ArcPy.  Is it okay to use?

**Comment by steveoh** [comment]
It doesn't yet, you still need to `str(Path)` but I would prefer we all get familiar with the new module and it's api and in the habit of using it.

**Comment by eneemann** [comment]
So something like `str(Path(egdb) / result)`?

**Comment by steveoh** [comment]
Well, I would suggest probably going a bit higher to `egdb = credentials.DB` then then it would be `str(egdb / fc)`

**Review by steveoh — CHANGES_REQUESTED** [review]
nice, then can the os import be remove?

**Comment by eneemann** [comment]
looks like it, yeah

**Review by steveoh — APPROVED** [review]

**Pull request merged**
